[[SPIRV_Cross]]
arch = "aarch64"
git-tree-sha1 = "a5dddbda842069828a68c84cdd809171518ef61c"
os = "macos"

    [[SPIRV_Cross.download]]
    sha256 = "124caf165e3aeebcc796c2248a74a29121fbd040795c1995de84f7d6a0e6f579"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.aarch64-apple-darwin.tar.gz"
[[SPIRV_Cross]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6aefa0d7464f921302805d02f3a0aca38e54556b"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "bc3a3a68079daf522dc1687f45ccf676cda0159405df0c7fabe8f0ff63e589e1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b4d82a48e723799e9433c28ce99702a599c3480"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "bdd43d0ddbfd08a14e1b0f4b40a80ea3a1ead937185df047890a117f99d30650"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cde753e6449106b688341b0358fbb0ffdfa4d12d"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "8eee6f333af5e184562d7202dafb8f84ec6e3e34bc685b33c9d0094125c64d00"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6629fb92d15bf8dd980471e8a39710ce6d7e2561"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "9edafc69a5288bc559afca67a898f0c342a9ddaa544eab3810222fd59f8a8c67"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b463063eae49a4c8b32519830ed86a8ddb5c7d4"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "3f21290672cf0046ba49cd543d2d0fa76325418e60d591af2e6d920dcfc03f25"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02b449a9c18c6825cfed5fd79b6694cc9936d896"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "137b878b12cd86db8c33046930c5d91a0cc3ef313db77821890b1b9c9f1ea7f1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "369f3d1edd825b9bfb099155044751d4cbe08056"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "a04574fca6022de88eedd3cde130598a8f2650c3690c4c6344bc4dbed05817a2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd0cff5a99a0469d9839607aff2371c78580dd4b"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "8dee95bc1313c06c8ac753bf57ee9d64d2d2ce85908d6e0553a254956fea3543"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9e6e615ffc559a3dddadd3cb2b69add298b5c39"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "29a44133c66123a20530e0c5b981a7840e2bddf14d13bd35eac4da23232d36af"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408683e36e46f89a2e874c3ce10e7fbdec1488b2"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "8a8a3d4d83ede95232cf521bcec07c550c76c44940c39ed4676843618d7ce740"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "133bed7767cd46f7dee2e58c2c996db1c0cd3359"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "ef913244d3b9166d8ce08965e5c93101f269a768bbfeaaa0261e91b20a8eacca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edaf1449970c18f7809cbd940ba538b980a791cf"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "5960f98e55018120f9cbc111259b78fefa9e26a4bdb41ac3baae4b9d007363de"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30ba8d169d400f8611e819ae7ed49c7f0d62b9a9"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "3005bcc42637047dac0959a334496068045a684fb076862ab0b62f59d2fe7141"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7abb9971b7d026cbf4e98925b11736072780efec"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "21e5de36841594d3f58fadca3ea5909dd8b44ebffcd04cdb90de7a95b2201745"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e1cd237e620bffb4c3b280a4d78c1bd52d04cfb"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "bd93085e10d1bfd4b317ae274805de6601e2091dc3d7a6f3d62ca2088fac324d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd6faac191b512b2fd4348386920f4aa8624ea27"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "b5cff49c8c26a15df0914ef9e6ff0b33973cc9f6cd319b90ca48edc795bcbc23"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d13d58f2c5fecdb13920236f155a8cdbb3c175c"
os = "windows"

    [[SPIRV_Cross.download]]
    sha256 = "433f28c974493c4bf304f1aa600469d474dd3953141de5103d82402fcf6dc5bd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f82f3b69c5a394b6f145823e1cf06c9b18d5d1b"
os = "windows"

    [[SPIRV_Cross.download]]
    sha256 = "d9e295150a3e5b13aa3aff3543fd08f71280c8f49bcca1352aad6dcfd76b2254"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e040f0887ec65d0c125080b0f2619652c725486"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "445de3841cb1e9c700bdae480f97184524de2cc3e3956710399bac011cce1f20"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53d99bb9ef56f135b2e3bc081482c248d0dc3f5e"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "91d41c03dfe4f4b53a44417fd5e58760a0fce592529d0526d2c74a5a58238c2b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
git-tree-sha1 = "c359ac526ffda95c5a56c856e73bdcf52523de3c"
os = "macos"

    [[SPIRV_Cross.download]]
    sha256 = "5cf9c6f84312a48b8b3a65cfb9891884998ec206812799088aca027b3ac15ca2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-apple-darwin.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9be77b4732f98e5480440ce8fa6937042d4aa584"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "cdc537ab9fcc1b82c46de710ae8ee792d4b8c460bed4c0d2020706bca9ff35f1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d06a9246d7bbbb5e34ed970650a1de17b2f766e"
libc = "glibc"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "8da0f761b04798e7806003da5a35d3b70686a5bfb4a96180967665548e4c8058"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2734a6ba80392fd04833c190782a784edc5da1ad"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "7b827142bda319f3bcbf52a8fdf66730bea9f03371d0a8fd734e74d7bfa9fa30"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "967f974672968bbdc8f400bbf7efc50bde1ebbb2"
libc = "musl"
os = "linux"

    [[SPIRV_Cross.download]]
    sha256 = "8f858d23b6b6de4b6de74dea4aa79192345ed6b80fb6526ed9ee9773f7f604d7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
git-tree-sha1 = "0e5a6310d02b400e9985212de3745fceceaaf446"
os = "freebsd"

    [[SPIRV_Cross.download]]
    sha256 = "bb55e470b78c00ea4403a5b4c90de31eac50783779c2a0567b4c02f4675d8ac2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c70b2ab16fceb602a72e9fed9e63b0dacf428f4c"
os = "windows"

    [[SPIRV_Cross.download]]
    sha256 = "effbbf112c46f2415dba2466125ce99c772bd879709189226f8ee9f8e3b0c68e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Cross]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5efb547db97626706059031d4a230f147433b98b"
os = "windows"

    [[SPIRV_Cross.download]]
    sha256 = "9302a4ff8444f4b1d5b8113e8295ba8d4450bec0ef3da04711e11292598a0d25"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Cross_jll.jl/releases/download/SPIRV_Cross-v2021.1.15+0/SPIRV_Cross.v2021.1.15.x86_64-w64-mingw32-cxx11.tar.gz"
